users/applications/Users/urls.py
from . import views
from django.urls import path

app_name = "users_app"

urlpatterns = [
    path(
        'register/',
        views.UserRegisterView.as_view(),
        name="user-register"
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name="user-login"
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name="user-logout"
    ), 
    path(
        'update/',
        views.UpdatePasswordView.as_view(),
        name="user-update"
    ),          
    path(
        'user-verification/<pk>/',
        views.CodeVerificationView.as_view(),
        name="user-verification"
    ),
]

users/applications/home/urls.py
from . import views
from django.urls import path

app_name = "home_app"

urlpatterns = [
    path(
        'panel/',
        views.HomePage.as_view(),
        name="panel"
    ),
    path(
        'mixin/',
        views.TemplatePruebaMixin.as_view(),
        name="mixin"
    ),
]

users/users/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.Users.urls')),
    path('', include('applications.home.urls'))
]

users/applications/home/models.py
from django.db import models

# Create your models here.

users/applications/home/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin # mixin to redirect user when it's not login
from django.views.generic import TemplateView
from django.urls import reverse_lazy

class FechaMixin(object):
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["fecha"] = datetime.datetime.now()
        return context
    

class HomePage(LoginRequiredMixin, TemplateView):
    template_name = 'home/index.html'
    login_url = reverse_lazy('users_app:user-login') # attr necessary to redirect


class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = "home/mixin.html"
    

users/templates/home/index.html
{% extends 'base.html' %}

{% block title %}
    Inicio
{% endblock title %}


{% block content %}
    <h1>Bienvenidos al inicio: {{user}}</h1>
    <ul>
        <li>
            <a href="{% url 'users_app:user-logout' %}">Cerrar seccion</a>
        </li>
        <li>
            <a href="{% url 'users_app:user-update' %}">Actualizar datos</a>
        </li>
    </ul>
{% endblock content %}
    

users/templates/home/mixin.html
{% extends 'base.html' %}


{% block content %}
    <h1>Fecha {{ fecha }}</h1>
{% endblock content %}
    